const plants = [
  {
    common_name: "Monstera",
    plant_origin: "Central America",
    scientific_name: ["Monstera deliciosa"],
    type: "Indoor",
    cycle: "Perennial",
    description: "Monstera is known for its large, glossy, split leaves.",
    sunlight: "Bright, indirect light",
    watering: "Water when the top inch of soil is dry",
    depth_of_water: "Moderate",
    last_watered: "2024-08-18",
    next_watering: "2024-08-25",
    watering_general_benchmark: { min: "Weekly", max: "Biweekly" },
    watering_period: "Weekly",
    volume_water_requirement: { min: "500ml", max: "1L" },
    pruning_month: ["March", "April"],
    pruning_count: { times_per_year: 2 },
    maintenance: "Low",
    growth_rate: "Moderate",
  },
  {
    common_name: "Snake Plant",
    plant_origin: "West Africa",
    scientific_name: ["Sansevieria trifasciata"],
    type: "Indoor",
    cycle: "Perennial",
    description:
      "Snake Plant is a low-maintenance plant known for its upright leaves.",
    sunlight: "Low to bright indirect light",
    watering: "Water when the soil is completely dry",
    depth_of_water: "Low",
    last_watered: "2024-08-17",
    next_watering: "2024-08-24",
    watering_general_benchmark: { min: "Biweekly", max: "Monthly" },
    watering_period: "Biweekly",
    volume_water_requirement: { min: "200ml", max: "500ml" },
    pruning_month: ["May", "June"],
    pruning_count: { times_per_year: 1 },
    maintenance: "Very Low",
    growth_rate: "Slow",
  },
  {
    common_name: "Aloe Vera",
    plant_origin: "Arabian Peninsula",
    scientific_name: ["Aloe vera"],
    type: "Indoor/Outdoor",
    cycle: "Perennial",
    description: "Aloe Vera is a succulent known for its medicinal properties.",
    sunlight: "Bright, indirect light",
    watering: "Water when the soil is completely dry",
    depth_of_water: "Low",
    last_watered: "2024-08-20",
    next_watering: "2024-08-27",
    watering_general_benchmark: { min: "Biweekly", max: "Monthly" },
    watering_period: "Biweekly",
    volume_water_requirement: { min: "100ml", max: "300ml" },
    pruning_month: ["July", "August"],
    pruning_count: { times_per_year: 2 },
    maintenance: "Low",
    growth_rate: "Moderate",
  },
  {
    common_name: "Spider Plant",
    plant_origin: "Southern Africa",
    scientific_name: ["Chlorophytum comosum"],
    type: "Indoor",
    cycle: "Perennial",
    description:
      "Spider Plant is known for its arching leaves and small white flowers.",
    sunlight: "Indirect light",
    watering: "Water when the soil is moderately dry",
    depth_of_water: "Moderate",
    last_watered: "2024-08-15",
    next_watering: "2024-08-22",
    watering_general_benchmark: { min: "Weekly", max: "Biweekly" },
    watering_period: "Weekly",
    volume_water_requirement: { min: "300ml", max: "600ml" },
    pruning_month: ["September", "October"],
    pruning_count: { times_per_year: 3 },
    maintenance: "Medium",
    growth_rate: "Fast",
  },
  {
    common_name: "Fiddle Leaf Fig",
    plant_origin: "West Africa",
    scientific_name: ["Ficus lyrata"],
    type: "Indoor",
    cycle: "Perennial",
    description:
      "Fiddle Leaf Fig is a popular houseplant known for its large, violin-shaped leaves.",
    sunlight: "Bright, indirect light",
    watering: "Water when the top inch of soil is dry",
    depth_of_water: "High",
    last_watered: "2024-08-19",
    next_watering: "2024-08-26",
    watering_general_benchmark: { min: "Weekly", max: "Biweekly" },
    watering_period: "Weekly",
    volume_water_requirement: { min: "1L", max: "2L" },
    pruning_month: ["January", "February"],
    pruning_count: { times_per_year: 2 },
    maintenance: "High",
    growth_rate: "Slow",
  },
  {
    common_name: "Peace Lily",
    plant_origin: "Tropical Americas",
    scientific_name: ["Spathiphyllum"],
    type: "Indoor",
    cycle: "Perennial",
    description:
      "Peace Lily is known for its white blooms and air-purifying qualities.",
    sunlight: "Low to bright indirect light",
    watering: "Keep the soil consistently moist",
    depth_of_water: "Moderate",
    last_watered: "2024-08-16",
    next_watering: "2024-08-23",
    watering_general_benchmark: { min: "Weekly", max: "Weekly" },
    watering_period: "Weekly",
    volume_water_requirement: { min: "400ml", max: "800ml" },
    pruning_month: ["November", "December"],
    pruning_count: { times_per_year: 2 },
    maintenance: "Low",
    growth_rate: "Moderate",
  },
  {
    common_name: "ZZ Plant",
    plant_origin: "Eastern Africa",
    scientific_name: ["Zamioculcas zamiifolia"],
    type: "Indoor",
    cycle: "Perennial",
    description:
      "ZZ Plant is a tough, drought-tolerant plant with glossy leaves.",
    sunlight: "Low to bright indirect light",
    watering: "Water when the soil is completely dry",
    depth_of_water: "Low",
    last_watered: "2024-08-21",
    next_watering: "2024-08-28",
    watering_general_benchmark: { min: "Monthly", max: "Bimonthly" },
    watering_period: "Monthly",
    volume_water_requirement: { min: "200ml", max: "400ml" },
    pruning_month: ["March", "April"],
    pruning_count: { times_per_year: 1 },
    maintenance: "Very Low",
    growth_rate: "Slow",
  },
];

module.exports = { plants };
